name: Python unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CRDS_SERVER_URL: https://jwst-crds.stsci.edu
  CRDS_PATH: $HOME/crds_cache
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.21.3
        pip install pandas==1.4.1
        pip install scipy==1.7.1
        pip install jwst==1.4.3
        pip install matplotlib==3.4.3
    - name: Test with builtin unittesting
      run: |
        python -m unittest tests/test_drop_groups.py
