name: Python unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  CRDS_SERVER_URL: https://jwst-crds.stsci.edu
  CRDS_PATH: $HOME/crds_cache
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        conda init zsh
        conda activate base
        python -m pip install --upgrade pip
        pip install numpy
        pip install pandas
        pip install scipy
        pip install jwst
        pip install matplotlib
    - name: Test with builtin unittesting
      run: |
        python -m unittest tests/test_drop_groups.py
