name: build wheels and upload to test pypi

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build a pure python wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build wheel and source distribution
        run: pipx run build

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
